# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Provision
    displayName: 'Terraforming on AWS...'
    jobs:
    - job: Provision
      displayName: 'Provisioning Instance'
      pool:
        vmImage: 'ubuntu-latest'
      variables: 
      - group: TeraformEnvVars
      steps:
      - script: |
          set -e
          terraform init
          terraform workspace new Development
          terraform plan -out development.tfplan
          terraform apply "development.tfplan"
      name: 'RunTerraform'
      displayName: 'Run Terraform'
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)